name: Laravel Test

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  laravel-tests:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: laravel
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.action', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install Node.js and Dependencies
        run: npm ci

      - name: Build assets with Vite
        run: npm run build

      - name: Run migrations
        run: php artisan migrate --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_HOST: localhost
          DB_CONNECTION: pgsql
          DB_DATABASE: laravel
          DB_PASSWORD: postgres
          DB_USERNAME: postgres
          DB_PORT: 5432
        run: vendor/bin/phpunit
